<h1>Numpy</h1>

<h2>Por qué Numpy?</h2>

Nos permite realizar operaciones con matrices numéricas.

Ventajas: Velocidad , Funcionalidad , Interoperabilidad.

Nos permite crear Ndarray.

Podemos observar el tipo de dato del array usando el .type(array) que nos devuelve que es de tipo ndarray.
Ejemplo : un_array=np.array([7,77,777]) es un array de una dimensión con un tamaño de 3.
Con el array.shape podemos observar el tamaño y dimensión del array que se le pasa al método.
 

In [2]:
import numpy as np

arr1=np.array([7,77,777])
print(arr1)
print(type(arr1))
print(arr1.shape)

[  7  77 777]
<class 'numpy.ndarray'>
(3,)


Si queremos tener un array de dos dimensiones o más se debe dividir los datos dentro de [] por una , de esta manera el array se convierte en un plano.
Ejemplo: un_array2=([[7,77,777],[7,77,777]]) esto es un array de dos dimensiones. Es un array de 2x4 dos filas y 4 columnas.
Consejo: El primer dato muestra siempre las filas y el segundo las columnas.

In [3]:
import numpy as np
arr2=np.array([[7,77,777,7777],[7,777,7777,45]])
print(arr2)

[[   7   77  777 7777]
 [   7  777 7777   45]]


Para acceder a los valores de un array es suficiente con llamar al array y pasarle entre [ ] las posición del valor que quiero acceder.
Ejemplo: print(array[0])

In [4]:
print(arr2[1][1])

777


<h2>Array Multidimesional</h2>

Ejemplo :
multidimensional=np.array([[1,5,4],[7,8,9],[5,6,7]]) esto es un array 3x3.

In [5]:
multidimensional=np.array([[1,5,4],[7,8,9],[5,6,7]])
print(multidimensional)

[[1 5 4]
 [7 8 9]
 [5 6 7]]


Para acceder a la posición de un dato en un array multidimensional se especifica la fila y luego la columna en la que va a recorrer entre [ ][ ]
Ejemplo:
multidimensional[2][0].

In [6]:
print(multidimensional[2][0])

5


Consejo: Las posiciones de un array comienzan en 0.

<h2>Distintas maneras de crear ndarrays</h2>

Array lleno de ceros
ej1=np.zeros((1080,1920))

In [7]:
ej1=np.zeros((1080,1920))
print(ej1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Este metodo zeros(()) crea un array lleno de 0. Se especifica la cantidad de filas y columnas. Separados por comas.

El método np.full((y,z),x) crea un array de una dimension especificada con y,z y=filas y z=columnas , y  x especifica el número con el que se va a llenar dicho array.

In [8]:
arr3=np.full((2,2),5)
print(arr3)

[[5 5]
 [5 5]]


<h2>Arrays de indice e indexado booleano</h2>

In [9]:
array_a=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print(array_a)
print(array_a.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
(4, 3)


Con el método np.arange(x) se puede crear arrays donde x indica el número hasta donde va a contar.

In [10]:
cols=np.array([0,1,2,0])
rows=np.arange(4)
print("Filas:",rows)
print("Columnas:",cols)

Filas: [0 1 2 3]
Columnas: [0 1 2 0]


In [11]:
for row , col in zip(rows,cols):
    print("Rows:",row,"Cols:",col)

Rows: 0 Cols: 0
Rows: 1 Cols: 1
Rows: 2 Cols: 2
Rows: 3 Cols: 0


In [12]:
print(array_a[rows,cols])

[11 22 33 41]


Haciendo uso de los [x,y ] con un array se pueden modificar el valor de los datos cuyan posición marcan los índices. Ejemplo a continuación:

In [13]:
print(array_a)
array_a[rows,cols]+=1000
print(array_a)

[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]
[[1011   12   13]
 [  21 1022   23]
 [  31   32 1033]
 [1041   42   43]]


Tambien se pueden crear filtros a los arrays de una forma muy fácil.

In [14]:
array_b=np.array([[11,12],[21,22],[31,32]])
print(array_b)
print("********************")
print(array_b.shape)

[[11 12]
 [21 22]
 [31 32]]
********************
(3, 2)


In [15]:
filtro= (array_b>15)
#Aqui se crea el filtro para usarlo posteriormente
print(filtro)
filtrado=array_b[filtro]
print("***************")
print(filtrado)

[[False False]
 [ True  True]
 [ True  True]]
***************
[21 22 31 32]


De la anterior forma el filtro solamente toma los valores que devuelven True y al pasarselo a un array este solamente muestra los valores de la posición  donde devolvió True lo que en forma de datos.

Aunque no es necesario crear el filtro previamente , simplemente se le pasa ya la condición directamente al array.

In [16]:
print(array_b[(array_b%2==0)])
#Esto muestra los numeros pares.

[12 22 32]


El uso principal de estos filtros es para modificar los datos de un array donde se cumplan las condiciones deseadas.

In [17]:
array_b[array_b%2==0]+=1000
print(array_b)

[[  11 1012]
 [  21 1022]
 [  31 1032]]


<h2>Slices</h2>

Hacer un slice en un array sirve para aislar una "sub-región" de la matriz de un ndarray

In [18]:
un_array=np.array([[11,12,13,14,15,16],[21,22,23,24,25,26],[31,32,33,34,35,36],[41,42,43,44,45,46]])
print(un_array)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]


Crearemos un slice de 2x2 a partir de un_array

Consejo:En el siguiente caso nótese que al limitar el slice al 2 esta posición no se cuenta. Por tanto llegaría solamente a los datos del 0 al 1, igualmente en el caso de 1:3 limitará desde el 1 al 2. La primera limitación se realiza en las filas y la 2 en las columnas. Por tanto el números que marca el final no se incluye.

In [19]:
un_slice=un_array[0:2,1:3]
print(un_slice)

[[12 13]
 [22 23]]


Entonces luego de marcar la sub-region como se hizo anteriormente entonces se crea un slice a la misma donde se marca el dato a mostrar.

In [20]:
print("Slice:",un_slice[0,0])

Slice: 12


Entonces podriamos modificar la posición que logramos obtener.

In [21]:
un_slice[0,0]+=100
print("Slice:",un_slice[0,0])

Slice: 112


Ahora al llamar al array principal de donde partió , de donde se saco la sub-región originalmente nótese que también cambió su valor, debido a que estuvimos trabajando en ese array principal desde el principio. Lo que de esta forma se facilitó su acceso ya que al delimitar su región las posiciones pasan a empezar desde 0 y es como si estuviéramos trabajando con un pequeño array.

Realmente un_slice es un puntero.

In [22]:
print(un_array)

[[ 11 112  13  14  15  16]
 [ 21  22  23  24  25  26]
 [ 31  32  33  34  35  36]
 [ 41  42  43  44  45  46]]


Si necesito sacar un nuevo array a partir de un slice simplemente se crea uno nuevo lo que se le pasa el slice.

In [23]:
nuevo_array=np.array(un_slice)
print(nuevo_array)

[[112  13]
 [ 22  23]]


<h2>Tipos de datos ndarray y operaciones</h2>

In [24]:
ej1=np.array([11,12])
print(ej1.dtype)

int32


In [25]:
ej1=np.array([11.2,12.3])
print(ej1.dtype)

float64


Tambien se pueden forzar el tipo de dato.

In [26]:
ej3=np.array([11,12],dtype=np.float64)
print(ej3.dtype)

float64


Operaciones Aritméticas

In [27]:
x=np.array([[111,112],[121,122]])
y=np.array([[211.1,212.1],[221.1,222.1]])
print(x.dtype)
print(y.dtype)

print(x-y)

int32
float64
[[-100.1 -100.1]
 [-100.1 -100.1]]


También se puede usar con el método .subtract(x-y)

In [28]:
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]


Igualmente se pueden hacer las siguientes operaciones:


In [29]:
print(x*y)#Tambien se puede usar np.multiply(x,y)
print("***************")
print(x/y)#Tambien se puede usar np.divide(x,y)
print("***************")
print(np.sqrt(x,y))#Raíz cuadrada

[[23432.1 23755.2]
 [26753.1 27096.2]]
***************
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
***************
[[10.53565375 10.58300524]
 [11.         11.04536102]]


Estadísticas Básicas

In [30]:
#Generar un array aleatorio
arr=10*np.random.randn(2,5)
print(arr)

[[15.68788167 -1.03261976 -7.09708194 -1.31226262  9.10642806]
 [-1.44348916 -1.10584967 -5.83180806  4.64285266  0.41596512]]


In [31]:
#Con mean() calcula el promedio de un array
print(arr.mean())

1.203001630151868


In [32]:
#Calcular el promedio pero en este caso fila por fila
print(arr.mean(axis=1))

[ 3.07046908 -0.66446582]


In [33]:
#Calcular el promedio pero en este caso por columna
print(arr.mean(axis=0))

[ 7.12219626 -1.06923472 -6.464445    1.66529502  4.76119659]


Con sort() se ordena los arrays

In [34]:
arr.sort()
print(arr)

[[-7.09708194 -1.31226262 -1.03261976  9.10642806 15.68788167]
 [-5.83180806 -1.44348916 -1.10584967  0.41596512  4.64285266]]


Con el método np.unique(array) busca los elementos unicos del array.
MUY UTIL

In [35]:
un=np.array([1,2,4,1,3])
print(np.unique(un))

[1 2 3 4]


<h2>Operaciones en conjunto</h2>

In [36]:
s1=np.array(["silla","mesa","escritorio"])
s2=np.array(["escritorio","silla","lampara"])
print(s1)
print(s2)

['silla' 'mesa' 'escritorio']
['escritorio' 'silla' 'lampara']


In [37]:
#Interseccion
print(np.intersect1d(s1,s2))

['escritorio' 'silla']


In [38]:
#Union en 1d
print(np.union1d(s1,s2))

['escritorio' 'lampara' 'mesa' 'silla']


In [39]:
#Que elementos de s1 no estan en s2 (Devuelve valores booleanos)
print(np.in1d(s1,s2))

[ True False  True]


In [40]:
#Elementos de s1 que no estan en s2
print(np.setdiff1d(s1,s2))

['mesa']


<h2>Operaciones Frecuentes</h2>

Para sumar todos los datos dentro de un array

np.sum(array)

In [41]:
ex1=np.array([[11,12],[21,22]])
print(np.sum(ex1))

66


Sumar solo una columna


np.sum(array,axis=0)


Sumar una fila 


np.sum(array,axis=1)

In [44]:
print(ex1)
print("*******")
print(np.sum(ex1,axis=0))
print(np.sum(ex1,axis=1))

[[11 12]
 [21 22]]
*******
[32 34]
[23 43]


Reformatear un array

Primero se crea el array y con el .reshape() se cambia su forma. 

In [45]:
arr=np.arange(20) #array unidimensional
print(arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Se convirtió el array anterior en un 4x5 en el siguiente ejemplo.

In [46]:
reshaped_arr=arr.reshape(4,5)
print(reshaped_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Transponer o transposicionar un array

In [48]:
print(ex1)
print("********")
print(ex1.T)

[[11 12]
 [21 22]]
********
[[11 21]
 [12 22]]


Where .... UTIL

In [49]:
mat=np.random.rand(4,4)
print(mat)

[[0.97746025 0.63586794 0.59390208 0.49283084]
 [0.86247791 0.22750513 0.89262227 0.51447225]
 [0.22397743 0.76513048 0.43729726 0.23504079]
 [0.86853031 0.88530567 0.922673   0.33902414]]


Ahora se le pasa el metodo np.where(array<>condicion,si cumple remplaza por esto,si no por esto).Ejemplo a continuacion:

In [51]:
print(np.where(mat>0.5, 1, 0))

[[1 1 1 0]
 [1 0 1 1]
 [0 1 0 0]
 [1 1 1 0]]


Con array.any() podemos comprobar si existe algun dato distinto de 0 , esto funcionar tanto para los booleanos True y False.

In [53]:
ex2=np.array([0,0,0,0])
print(ex2.any())
#Si modificamos algun valor del array por cualquier numero que no sea 0 devuelve True.
ex2=np.array([1,0,0,0])
print(ex2.any())

False
True


Con el metodo array.all() podemos comprobar si existe algun dato que no sea True.

In [54]:
ex3=np.array([1,1,0])
print(ex3.all()) #Devuelve False porque no todos los elementos son True.

False


Tambien existen metodos para unir dos arrays. 

np.vstack((array1,array2)) #Tambien se puede usar el metodo concatenate(axis=0 o 1)


np.hstack((array1,array2))

Existe tambien la propagacion se arrays al sumarle una fila o una columna a un array este debe tener el mismo tamaño , para sumar una columna al array luego de haber creado el array unidimensional que se desea propaganar se debe verticalizar con el metodo .T .

<h2>Grabar un array</h2>

In [55]:
x=np.array([23.23,24.24])
np.save('array_prueba_save',x)


Para cargar el array ya guardado.


In [56]:
recuperado=np.load('array_prueba_save.npy')
print("Se recuperó el array:",recuperado)

Se recuperó el array: [23.23 24.24]
